
skillMetadata:
  sections:
    - name: Local Hubitat Information
      fields:
        - type: label
          label: This is where you specify your Hubitat's access token (from maker app) and local address
        - name: local_address
          type: text
          label: Dotted quad or hubitat.local
          value: "hubitat.local"
        - name: access_token
          type: text
          label: Token from maker app
          value: ""
        - name: minimum_fuzzy_score
          type: number
          label: Device name match score 0-100.
          value: 65
        - name: attr_name
          type: text
          label: attr1
          value: "temperaturesetPoint"
        - name: dev_name      
          type: text
          label: dev1     
          value: "thermometer thermometer"

